# import re

# class ResponseValidator:
#     def __init__(self):
#         # Keywords indicating system prompt leakage
#         self.leakage_keywords = [
#             r"untrusted_context",
#             r"PromptShield Assistant",
#             r"CRITICAL SECURITY DIRECTIVES",
#             r"REFERENCE CONTEXT",
#             r"system instructions",
#             r"ignore previous instructions",
#         ]

#     def validate(self, response_text, user_query, retrieved_chunks):
#         """
#         Validates LLM output before sending it to the user.
#         Checks for:
#         1. System prompt exfiltration.
#         2. Groundedness (does it contain hallucinated or outside information).
#         3. Compliance with security controls (e.g. refused to execute injected overrides).
        
#         Returns:
#             dict: { "is_safe": bool, "reason": str, "filtered_response": str }
#         """
#         if not response_text:
#             return {
#                 "is_safe": False,
#                 "reason": "Empty response generated by LLM.",
#                 "filtered_response": "Error: Empty response generated."
#             }

#         # 1. Check for system prompt leakage
#         for pattern in self.leakage_keywords:
#             if re.search(r'(?i)' + pattern, response_text):
#                 return {
#                     "is_safe": False,
#                     "reason": f"System leakage detected (matched security rule: {pattern}).",
#                     "filtered_response": "Security Violation: The response was blocked because it attempted to leak system instructions."
#                 }

#         # 2. Check for exfiltration of configuration or tokens (e.g. JWT strings or key patterns)
#         jwt_pattern = r"eyJhbGciOi[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+"
#         if re.search(jwt_pattern, response_text):
#             return {
#                 "is_safe": False,
#                 "reason": "JWT exfiltration detected in output.",
#                 "filtered_response": "Security Violation: Response blocked to prevent token exfiltration."
#             }

#         # 3. Groundedness Heuristic
#         # If the model says it cannot find info, it is safe
#         refusal_phrases = [
#             "do not contain enough information",
#             "not enough information",
#             "no information found",
#             "i am sorry, but",
#             "provided documents do not",
#             "cannot answer"
#         ]
#         is_refusal = any(phrase in response_text.lower() for phrase in refusal_phrases)
        
#         if not is_refusal and retrieved_chunks:
#             # Check if there's any semantic overlap between response and context chunks
#             # A simple intersection of content words (excluding stopwords)
#             stopwords = {'the', 'a', 'an', 'and', 'or', 'but', 'is', 'are', 'was', 'were', 'to', 'of', 'in', 'on', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'from', 'up', 'down', 'in', 'out', 'off', 'over', 'under', 'again', 'further', 'then', 'once'}
            
#             response_words = set(re.findall(r'\b\w{4,}\b', response_text.lower())) - stopwords
#             context_text = " ".join(retrieved_chunks).lower()
#             context_words = set(re.findall(r'\b\w{4,}\b', context_text)) - stopwords
            
#             # If the response shares almost no overlap with context but is long, it might be hallucinated/un-grounded
#             if len(response_words) > 5 and len(context_words) > 0:
#                 overlap = response_words.intersection(context_words)
#                 overlap_ratio = len(overlap) / len(response_words)
                
#                 # If overlap ratio is extremely low (e.g., < 5%), it's highly likely the LLM is answering from its own pre-trained knowledge
#                 # rather than the context, which could mean it followed a prompt injection to "talk about something else".
#                 if overlap_ratio < 0.05:
#                     return {
#                         "is_safe": False,
#                         "reason": f"Output groundedness failure (overlap ratio only {overlap_ratio:.1%}). Model may have hallucinated or bypassed context constraints.",
#                         "filtered_response": "Security Warning: The response was blocked because it was not grounded in the uploaded documents."
#                     }

#         return {
#             "is_safe": True,
#             "reason": "Response passed all validation checks.",
#             "filtered_response": response_text
#         }


import re


class ResponseValidator:

    def __init__(self):

        self.leakage_keywords = [
            r"untrusted_context",
            r"PromptShield Assistant",
            r"CRITICAL SECURITY DIRECTIVES",
            r"REFERENCE CONTEXT",
            r"system instructions",
            r"ignore previous instructions",
        ]

    def validate(self, response_text, user_query, retrieved_chunks):

        if not response_text:
            return {
                "is_safe": False,
                "reason": "Empty response.",
                "filtered_response": "Error: Empty response."
            }

        # -------------------------------------------------
        # 1. Prompt Leakage Detection
        # -------------------------------------------------

        for pattern in self.leakage_keywords:

            if re.search(pattern, response_text, flags=re.IGNORECASE):

                return {
                    "is_safe": False,
                    "reason": "System prompt leakage detected.",
                    "filtered_response":
                        "Security Violation: Prompt leakage detected."
                }

        # -------------------------------------------------
        # 2. JWT Detection
        # -------------------------------------------------

        jwt_pattern = r"eyJhbGciOi[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+"

        if re.search(jwt_pattern, response_text):

            return {
                "is_safe": False,
                "reason": "JWT detected.",
                "filtered_response":
                    "Security Violation: Token leakage blocked."
            }

        # -------------------------------------------------
        # 3. No document context
        # -------------------------------------------------

        if not retrieved_chunks:

            return {
                "is_safe": True,
                "reason": "General chatbot response.",
                "filtered_response": response_text
            }

        # -------------------------------------------------
        # 4. Ignore validation for obvious general questions
        # -------------------------------------------------

        general_keywords = [
            "capital",
            "population",
            "president",
            "prime minister",
            "who is",
            "what is",
            "where is",
            "when",
            "why",
            "2+2",
            "india",
            "python",
            "java",
            "ai",
            "machine learning"
        ]

        if any(k in user_query.lower() for k in general_keywords):

            return {
                "is_safe": True,
                "reason": "General knowledge question.",
                "filtered_response": response_text
            }

        # -------------------------------------------------
        # 5. Refusal responses are always safe
        # -------------------------------------------------

        refusal_phrases = [
            "not enough information",
            "do not contain enough information",
            "cannot answer",
            "i am sorry"
        ]

        if any(x in response_text.lower() for x in refusal_phrases):

            return {
                "is_safe": True,
                "reason": "Safe refusal.",
                "filtered_response": response_text
            }

        # -------------------------------------------------
        # 6. Groundedness Check
        # -------------------------------------------------

        stopwords = {
            "the","a","an","and","or","is","are","was","were",
            "this","that","with","from","into","about","over",
            "under","have","has","had","will","would","could"
        }

        response_words = (
            set(re.findall(r"\b\w{4,}\b", response_text.lower()))
            - stopwords
        )

        context_text = " ".join(retrieved_chunks).lower()

        context_words = (
            set(re.findall(r"\b\w{4,}\b", context_text))
            - stopwords
        )

        if response_words and context_words:

            overlap = response_words.intersection(context_words)

            overlap_ratio = len(overlap) / len(response_words)

            if overlap_ratio < 0.05:

                return {
                    "is_safe": False,
                    "reason":
                        f"Groundedness failure ({overlap_ratio:.1%}).",
                    "filtered_response":
                        "Security Warning: Response blocked because it was not grounded in the uploaded document."
                }

        # -------------------------------------------------

        return {
            "is_safe": True,
            "reason": "Passed validation.",
            "filtered_response": response_text
        }